# docker-compose.yml
services:
  render-backend:
    build: .
    container_name: render-backend
    restart: unless-stopped
    ports:
      - "14855:3000"
    env_file:
      - /home/ubuntu/app-69b6fb58161d976b43c95281/backend/.env
    volumes:
      - /home/ubuntu/app-69b6fb58161d976b43c95281/backend:/app
      - /app/node_modules
    networks:
      - appnet
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  appnet:

volumes:
  rabbitmq_data: